#!/bin/sh

# MIT License
#
# Copyright (c) 2024 Evelyn Lewis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# x800 gapless gameplay script
#
# This is a convenience script for x800 gameplay, as it provides the ability
# to play several games in a loop. It can be placed in the MacOS /Applications
# directory or a similar location on other OSs.

set -e

INTERNAL_BIN_PATH="/Applications/internal-x-eight-hundred"
SOURCE_BINARY_LOCATION="${HOME}/.cargo/bin/x800"

# Setup
if command -v "${SOURCE_BINARY_LOCATION}" && ! command -v ${INTERNAL_BIN_PATH}; then
	# If the usable bin path is already set, continue
	ln -s "${SOURCE_BINARY_LOCATION}" "${INTERNAL_BIN_PATH}"
else
	INTERNAL_BIN_PATH="$(which x800)"
fi

# Game loop
while true; do
	"${INTERNAL_BIN_PATH}"

	# Prompt for new game input. Note that the embedded newline and spaces
	# are intentional
	echo "
      press enter for a new game
"
	read -r input
	# To avoid unused variable
	echo "${input}" > /dev/null
done
