name: x800

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: rustup toolchain install stable --profile minimal
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: rustup toolchain install stable --profile minimal
      - name: Benchmarks
        run: |
          cargo install --quiet hyperfine
          ./util/bench.sh
          ./util/bench-stdin.sh

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: rustup toolchain install stable --profile minimal
      - name: Fuzz test
        run: |
          cargo install --quiet cargo-fuzz
          cargo fuzz run roger --sanitizer none --release -- -runs=0 > /dev/null
      - name: Fuzz coverage
        run: |
          rustup component add llvm-tools-preview
          ./util/coverage.sh
